---
# tasks file for lighthouse-role
 - name: Apply nginx config (Lighthouse)
   become: true
   ansible.builtin.template:
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf
     mode: 0644
 - name: Clone repository (Lighthouse)
   ansible.builtin.git:
     repo: "{{ lighthouse_url }}"
     dest: "{{ lighthouse_dir }}"
     version: master
 - name: Apply config (Lighthouse)
   become: true
   ansible.builtin.template:
     src: lighthouse_nginx.conf.j2
     dest: /etc/nginx/conf.d/lighthouse.conf
     mode: 0644
     notify: Nginx reload